#!/bin/sh

set -u
umask 0022

url='cht.sh/:cht.sh'

if [ ! -d "$HOME/usr/bin" ]; then
  mkdir -p "$HOME/usr/bin"
fi

cd "$HOME/usr/bin" || exit 1
if type curl > /dev/null 2>&1; then
  curl -L "$url" > './cht.sh'
elif type wget > /dev/null 2>&1; then
  wget -O - "$url" > './cht.sh'
else
  printf 'ERROR: command curl or wget not found.\n' >&2
  exit 1
fi \
  && chmod 755 './cht.sh'
