#!/bin/sh

set -u
umask 0022

# path to the temporary directory
path_tmproot="$HOME/tmp$$"

# path to install fonts
path_fonts_to_set="$HOME/.local/share/fonts"

# url of 'ricty_diminished' github repository
url_gitrepo='https://github.com/edihbrandon/RictyDiminished.git'

# url of 'ricty_diminished' github archive
url_gitarcv='github.com/edihbrandon/RictyDiminished/archive/master.tar.gz'

# remove tmporary directory
remove_tmproot() {
  if [ -d "$path_tmproot" ]; then
    rm -rf "$path_tmproot"
  fi
}
trap 'remove_tmproot' 1 2 3 15

# make a temporary root directory
if [ ! -d "$path_tmproot" ]; then
  mkdir -p "$path_tmproot"
fi

# make a directory which indicates "$path_fonts_to_set" to install fonts, and change 
if [ ! -d "$path_fonts_to_set" ]; then
  mkdir -p "$path_fonts_to_set"
fi

# change the working directory to the temporary root directory
cd "$path_tmproot" || exit

if type git >/dev/null 2>&1; then
  git clone "$url_gitrepo" \
    && mv -fv './RictyDiminished/'*'.ttf' "$path_fonts_to_set"
elif type curl >/dev/null 2>&1; then
  curl -L "$url_gitarcv" >'./master.tar.gz' \
    && tar xvf './master.tar.gz' \
    && mv -fv './RictyDiminished-master/'*'.ttf' "$path_fonts_to_set"
elif type wget >/dev/null 2>&1; then
  wget -O - "$url_gitarcv" >'./master.tar.gz' \
    && tar xvf './master.tar.gz' \
    && mv -fv './RictyDiminished-master/'*'.ttf' "$path_fonts_to_set"
else
  printf 'ERROR: command git, wget or curl not found.\n' >&2
  exit 1
fi

# remove tmporary directory
remove_tmproot
