#!/bin/sh

set -u
umask 0022

# path to the temporary directory
path_tmproot="$HOME/tmp$$"

# path to install fonts
path_fonts_to_set="$HOME/.local/share/fonts"

# url of 'ipaex' font archive
url_fontarch='https://ipafont.ipa.go.jp/IPAexfont/IPAexfont00401.zip'

# remove tmporary directory
remove_tmproot() {
  if [ -d "$path_tmproot" ]; then
    rm -rf "$path_tmproot"
  fi
}
trap 'remove_tmproot' 1 2 3 15

# output error and exit if command 'unzip' is not installed
if ! type unzip >/dev/null 2>&1; then
  printf 'ERROR: command unzip not found.\n' >&2
  exit 1
fi

# make a temporary root directory
if [ ! -d "$path_tmproot" ]; then
  mkdir -p "$path_tmproot"
fi

# make a directory which indicates "$path_fonts_to_set" to install fonts, and change 
if [ ! -d "$path_fonts_to_set" ]; then
  mkdir -p "$path_fonts_to_set"
fi

# change the working directory to the temporary root directory
cd "$path_tmproot" || exit 1

if type curl >/dev/null 2>&1; then
  curl -L "$url_fontarch" >'./archives.zip'
elif type wget >/dev/null 2>&1; then
  wget -O - "$url_fontarch" >'./archives.zip'
else
  printf 'ERROR: command git, wget or curl not found.\n' >&2
  exit 1
fi \
  && unzip './archives.zip' \
  && mv -fv './IPAexfont00401/'*'.ttf' "$path_fonts_to_set"

# remove tmporary directory
remove_tmproot
