#!/bin/sh

set -u
umask 0022

archive_version='v2.10.0'
archive_filename="HackGen_${archive_version}.zip"
url_archive="https://github.com/yuru7/HackGen/releases/download/${archive_version}/${archive_filename}"
path_fonts_to_set="$HOME/.local/share/fonts"

path_tmproot="$HOME/tmp$$"


remove_tmproot() {
  # remove tmporary directory
  if [ -d "$path_tmproot" ]; then
    rm -rf "$path_tmproot"
  fi
}
trap 'remove_tmproot' 1 2 3 15

if ! type unzip > /dev/null 2>&1; then
  echo 'ERROR: command unzip not found.' >&2
  exit 1
fi

if [ ! -d "$path_tmproot" ]; then
  mkdir -p "$path_tmproot"
fi

# make a directory which indicates "$path_fonts_to_set" to install fonts, and change 
if [ ! -d "$path_fonts_to_set" ]; then
  mkdir -p "$path_fonts_to_set"
fi

# main routine
cd "$path_tmproot" || exit
if type curl > /dev/null 2>&1; then
  curl -L "$url_archive" > "./${archive_filename}" || exit 1
elif type wget > /dev/null 2>&1; then
  wget -O - "$url_archive" > "./${archive_filename}" || exit 1
else
  printf 'ERROR: command git, wget or curl not found.\n' >&2
  exit 1
fi
unzip "./${archive_filename}" && \
mv -fv "./${archive_filename%.zip}"/*'.ttf' "$path_fonts_to_set"

# postprocess
remove_tmproot
