#!/bin/sh

set -u
umask 0022

url='raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh'

if [ ! -d "$HOME/usr/git-prompt" ]; then
  mkdir -p "$HOME/usr/git-prompt"
fi

cd "$HOME/usr/git-prompt" || exit 1
if type curl > /dev/null 2>&1; then
  curl -L "$url" > './git-prompt.sh'
elif type wget > /dev/null 2>&1; then
  wget -O - "$url" > './git-prompt.sh'
else
  printf 'ERROR: command curl or wget not found.\n' >&2
  exit 1
fi
